# Generated by Django 5.0.8 on 2024-12-02 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламаций'},
        ),
        migrations.AlterModelOptions(
            name='controlledaxle',
            options={'verbose_name': 'Модель управляемого моста', 'verbose_name_plural': 'Модель управляемых мостов'},
        ),
        migrations.AlterModelOptions(
            name='enginemodel',
            options={'verbose_name': 'Модель двигателя', 'verbose_name_plural': 'Модель двигателей'},
        ),
        migrations.AlterModelOptions(
            name='failurenode',
            options={'verbose_name': 'Модель узла отказа', 'verbose_name_plural': 'Модель узлов отказа'},
        ),
        migrations.AlterModelOptions(
            name='leadingaxle',
            options={'verbose_name': 'Модель ведущего моста', 'verbose_name_plural': 'Модель ведущих мостов'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'Модель ТО', 'verbose_name_plural': 'Модель ТО'},
        ),
        migrations.AlterModelOptions(
            name='organizationment',
            options={'verbose_name': 'Модель организации', 'verbose_name_plural': 'Модель организаций'},
        ),
        migrations.AlterModelOptions(
            name='recoverymethod',
            options={'verbose_name': 'Модель способа восстановления', 'verbose_name_plural': 'Модель способов восстановлений'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Модель сервисная компания', 'verbose_name_plural': 'Модель сервисных компаний'},
        ),
        migrations.AlterModelOptions(
            name='techmodel',
            options={'verbose_name': 'Модель техника', 'verbose_name_plural': 'Модель техники'},
        ),
        migrations.AlterModelOptions(
            name='transmissionmodel',
            options={'verbose_name': 'Модель трансмиссии', 'verbose_name_plural': 'Модель трансимиссий'},
        ),
        migrations.AlterModelOptions(
            name='typemaintenance',
            options={'verbose_name': 'Тип ТО', 'verbose_name_plural': 'Типы ТО'},
        ),
    ]
