# Generated by Django 5.0.8 on 2024-12-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0002_alter_car_options_alter_complaints_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['shipment_date'], 'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='complaints',
            options={'ordering': ['date_refusal'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламаций'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['date'], 'verbose_name': 'Модель ТО', 'verbose_name_plural': 'Модель ТО'},
        ),
    ]
