# Generated by Django 5.0.8 on 2024-12-12 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0004_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='organization_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='silant.organizationment', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
