# Generated by Django 5.0.8 on 2024-12-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0005_alter_maintenance_organization_maintenance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverymethod',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание способа восстановления'),
        ),
    ]
