# Generated by Django 5.0.8 on 2024-12-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silant', '0006_alter_recoverymethod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmissionmodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание трансмиссии'),
        ),
    ]
